### ISSUE TITLE
Error "seeker can't seek" when reading files not terminated by a newline

### ISSUE THREAD

**Issue by mcoffin** [mcoffin/s3proxy#8]
When you try to proxy a request for a file that isn't terminated by a newline, then you get the error `seeker can't seek`.

**Comment by dgramop** [comment]
Hm. That looks like the contents of the file /proc/buddyinfo

**Comment by mcoffin** [comment]
> Hm. That looks like the contents of the file /proc/buddyinfo

@dgramop wrong github issue?
